from pytorch/pytorch:1.3-cuda10.1-cudnn7-runtime
# set environment variables
ENV DEBIAN_FRONTEND noninteractive
ENV HDF5_USE_FILE_LOCKING FALSE
ENV NUMBA_CACHE_DIR /tmp

RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential libgl1-mesa-glx libglib2.0-0 libgeos-dev libvips-tools libffi-dev \
  sudo curl wget htop git vim ca-certificates  \
  && rm -rf /var/lib/apt/lists/*

RUN rm -rf /root/anaconda3
RUN rm -rf /root/.conda /root/.continuum /root/opt/anaconda3 /root/opt/conda /opt/conda
RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
RUN bash Miniforge3-Linux-x86_64.sh -b -p /opt/conda
ENV PATH=/opt/conda/bin:$PATH
RUN conda init
RUN conda install mamba -n base -c conda-forge

RUN pip install tensorflow[and-cuda]==2.16.2
RUN conda install -y openslide=3.4.1 -c conda-forge

WORKDIR /app
RUN git clone https://github.com/oval-group/smooth-topk.git
WORKDIR /app/smooth-topk
RUN python setup.py install

ENV TORCH_HOME /app/torch/
WORKDIR /app/torch/hub/checkpoints
RUN wget https://download.pytorch.org/models/resnet50-19c8e357.pth
RUN wget https://download.pytorch.org/models/densenet121-a639ec97.pth
RUN chmod -R 777 /app/torch/hub/checkpoints

RUN python -m pip install --upgrade pip
RUN pip install opencv-python openslide-python==1.3.1 scikit-learn matplotlib pandas albumentations tensorboardX 
RUN pip install numpy==1.*
RUN pip install torchvision==0.5.0
WORKDIR /.local
RUN chmod -R 777 /.local
WORKDIR /.cache
RUN chmod -R 777 /.cache


# bash at /App
WORKDIR /workspace
CMD ["/bin/bash"]