## ---------------------------------------------------------------------------
## rev1_incremental_value / 07_panel_figure.R
##
## Supplementary Figure panels -- Incremental value of BEACON over
## clinicopathological factors (Reviewer 3, major comment #1).
##   B. Decision curve, discovery cohort (primary, cohort-free)
##   C. Decision curve, combined cohort (secondary, cohort-stratified-adjacent)
##
## The former panel A (forest plot of the nested-Cox ladder, read from
## 03_summary_table.R's output) is superseded by 09_ladder_unstratified.R's
## own forest plot, which covers the same ground plus a 5th (unstratified
## whole-cohort) column, self-contained from a single set of fits rather
## than joined across files. 03_summary_table.R and its former panel A here
## were removed together (CE packaging decision) rather than kept as a
## narrower duplicate.
##
## Colour is shared with panel A's replacement in 09: flow, DACOR and BEACON
## keep one colour each everywhere they appear -- here as which model that
## marker was added to (CE, 2026-08-06) -- so the decision-curve panels and
## the forest plot cross-read as one figure even though they're generated by
## different scripts.
##
## House style otherwise: matches the two other rev1 forks (theme_bw(base_size
## =8-9)) so all rev1 supplementary figures read as one set. Panels B/C reuse
## 04_dca_nri.R's output rather than recomputing.
##
## Each panel is saved as its own individual PDF (CE, 2026-08-06) so it can be
## dropped into the manuscript directly without re-exporting.
## ---------------------------------------------------------------------------

REV1_DIR <- Sys.getenv("REV1_DIR", unset = NA_character_)
if (is.na(REV1_DIR)) {
  a <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
  REV1_DIR <- if (length(a)) dirname(sub("^--file=", "", a[1])) else "."
}
source(file.path(REV1_DIR, "00_config.R"))
suppressMessages({library(ggplot2); library(cowplot); library(scales)})

theme_rev1 <- theme_bw(base_size = 8) +
  theme(panel.grid.minor = element_blank(),
        strip.background = element_rect(fill = "grey92", colour = NA),
        strip.text = element_text(face = "bold", size = 7.5),
        plot.title = element_text(size = 9, face = "bold"),
        legend.position = "bottom", legend.title = element_blank(),
        legend.key.height = unit(3, "mm"))

## One colour per marker, shared by panel A (the marker itself) and panels
## B/C (the model that marker was added to). "clinical" (no marker added) is
## a neutral grey rather than reusing a marker colour, so it reads as "none"
## rather than implying an association with any one marker.
COL_MARKER <- c("Flow cytometry" = "#DD8452", "DACOR" = "#8172B2", "BEACON" = "#C44E52")
COL_MODEL  <- c("clinical" = "grey45", "clinical + flow" = "#DD8452",
                "clinical + DACOR" = "#8172B2", "clinical + BEACON" = "#C44E52")

read_latest <- function(pattern) {
  f <- sort(list.files(out_folder, pattern = pattern, full.names = TRUE), decreasing = TRUE)[1]
  if (is.na(f)) stop("no file matching ", pattern, " in ", out_folder)
  message("reading: ", basename(f))
  read.csv(f, stringsAsFactors = FALSE)
}

save_individual <- function(p, name, width, height) {
  P <- file.path(out_folder, sprintf("%s_%s.pdf", name, STAMP))
  ggsave(P, p, width = width, height = height)
  message("written: ", P)
}

## =============================================================================
## Panels B/C -- decision curves (reuse 04's output; shared colour w/ 09's
## forest plot, which replaces the former panel A here -- see header)
## =============================================================================
dca <- read_latest("^dca_curves_.*\\.csv$")
LEVELS <- c("treat all", "treat none", "clinical", "clinical + flow",
            "clinical + DACOR", "clinical + BEACON")
dca$model <- factor(dca$model, levels = LEVELS)

dca_panel <- function(set_key, title, ymax) {
  w <- dca[dca$set == set_key & !is.na(dca$model), ]
  ggplot(w, aes(threshold, net_benefit_corrected, colour = model)) +
    geom_line(aes(y = net_benefit), linewidth = 0.3, alpha = 0.28, na.rm = TRUE) +
    geom_line(linewidth = 0.7, na.rm = TRUE) +
    geom_hline(yintercept = 0, colour = "grey30", linewidth = 0.3) +
    scale_colour_manual(values = COL_MODEL, breaks = names(COL_MODEL)) +
    scale_x_continuous(labels = percent_format(accuracy = 1)) +
    coord_cartesian(ylim = c(-0.02, ymax)) +
    labs(title = title, x = "Threshold probability (5-year progression risk)", y = "Net benefit") +
    theme_rev1
}
## Titles kept short to fit panel width; the "secondary/cohort-confounded"
## caveat belongs in the figure legend prose, not squeezed into the title.
panelB <- dca_panel("discovery", "B   Decision curve -- discovery (primary)", 0.115)
panelC <- dca_panel("whole", "C   Decision curve -- combined (secondary)", 0.32)

save_individual(panelB, "figS7B_dca_discovery", 5.0, 3.6)
save_individual(panelC, "figS7C_dca_combined", 5.0, 3.6)

## =============================================================================
## Compose B+C (the forest plot that used to sit above these as panel A is
## now 09's own composite, produced from a single self-contained set of
## fits -- see header. No panel D either: the reclassification bar chart was
## dropped from the figure per CE; that information is Table S-Y.)
## =============================================================================
mid <- plot_grid(panelB, panelC, ncol = 2, rel_widths = c(1, 1))

P <- file.path(out_folder, sprintf("figS7BC_decision_curves_%s.pdf", STAMP))
ggsave(P, mid, width = 8.6, height = 3.6)
message("written: ", P)
